apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: edge-header-policy
  labels:
    global: "false"
plugin: edge-header-policy
config:
  request_exact_mode: append
  request_prefix_mode: append
  response_exact_mode: append
  response_prefix_mode: append
  request_allow_headers:
    - X-Request-Id
  request_allow_prefixes: []
  request_block_headers:
    - X-Forwarded-User
  request_block_prefixes: []
  response_allow_headers: []
  response_allow_prefixes: []
  response_block_headers:
    - X-Upstream-Service-Time
  response_block_prefixes:
    - x-debug-
